
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
google_analytics: G-313840737
url: http://asvid.github.io/

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Adam's Coding Corner | Adam Świderski | software engineer blog
      description: Writing around software engineering | Android | Kotlin | Programming
      page_title: Adam's Coding Corner

rss_path: feed.xml

feed:
  excerpt_only: true
  description: Adam Świderski blog
  posts_limit: 5
  title: Adam's Coding Corner | Adam Świderski | software engineer blog
  categories:
    - rss

categories_path: categories.html
tags_path: tags.html

BASE_PATH:
ABOUT: about
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  - jemoji
  - jekyll-toc
  - jekyll-diagrams

collections:
  - projects
  - technologies

languages: ["en", "pl"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: false
lang_from_path: true

sass:
  sourcemap: never

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter", "image size"]

toc:
  min_level: 1
  max_level: 2