
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: asvid
google_analytics: UA-68530276-7
title: Hi I'm Adam

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Asvid

description: Hi I'm Adam
author:
  name: Adam Świderski
  email: adam.swiderski89@gmail.com
  github: asvid
  twitter: _asvid
  linkedin: pl.linkedin.com/in/aswiderski
  bio: and I'm a programmer
  email_md5: c0092be8e7a926ead4c4a818ea622858

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: /assets/sa.jpg

BASE_PATH:

gems:
  - jekyll-paginate