
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: asvid
google_analytics: UA-68530276-7
url: http://asvid.github.io/

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: DevLog | Adam Świderski | software engineer blog
      description: Software engineering and architecture | Android | Programming
      page_title: DevLog

rss_description: Adam Świderski developer blog
author:
  name: Adam Świderski
  email: adam.swiderski89@gmail.com
  github: asvid
  linkedin: aswiderski
  bio_title: Hi I'm Adam
  bio: and I'm a software engineer
  disqus_bio: software engineer
  email_md5: c0092be8e7a926ead4c4a818ea622858

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: /assets/sa.jpg

BASE_PATH:
ABOUT: about
plugins:
  - jekyll-paginate
  - jekyll-crosspost-to-medium
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap

jekyll-crosspost_to_medium:
  enabled: false
  cache: .jekyll-crosspost_to_medium
  status: draft
  text: "<p><i>This article was originally posted <a href=\"http://asvid.github.io\" rel=\"canonical\">on my own site</a>.</i></p>"
  license: all-rights-reserved
  backdate: true

collections:
  - projects
  - technologies
